export const routes = {
  home: "/pages/home/index/index",
  accountIndex: "/pages/account/index/index",
  accountLink: "/pages/account/link/link",
  entrySearch: "/pages/entry/search/search",
  entryProfile: "/pages/entry/profile/profile",
  liveIndex: "/pages/live/index/index",
  liveEntry: "/pages/live/entry/entry",
  liveMatch: "/pages/live/match/match",
  liveTournament: "/pages/live/tournament/tournament",
  dataIndex: "/pages/data/index/index",
  dataPlayers: "/pages/data/players/players",
  dataPlayerDetail: "/pages/data/player-detail/player-detail",
  dataTeams: "/pages/data/teams/teams",
  dataTeamDetail: "/pages/data/team-detail/team-detail",
  dataPrice: "/pages/data/price/price",
  dataSelections: "/pages/data/selections/selections",
  summaryEntry: "/pages/summary/entry/entry",
  summaryTournament: "/pages/summary/tournament/tournament",
  summaryGameweek: "/pages/summary/gameweek/gameweek",
  myFplTeam: "/pages/my-fpl/team/team",
  myFplLeagues: "/pages/my-fpl/leagues/leagues",
  exploreFixtures: "/pages/explore/fixtures/fixtures",
  performance: "/pages/performance/index/index"
} as const;
